projects:
  quasarDemo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: r5c3cvd545cspe3rfkj6dsyloi
      endpoints:
        prod: >-
          https://7jqydoq2vzeoli64mmgydart2i.appsync-api.us-east-1.amazonaws.com/graphql
